References: https://www.youtube.com/watch?v=x9JiIFvlUwk

In [2]:
import torch

1. Initializing Tensor

In [4]:
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]])
my_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
my_tensor = torch.tensor([[1, 2, 3],
                          [4, 5, 6]], dtype=torch.float64, device='cpu', requires_grad=False)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [13]:
# other common initialization methods
x = torch.empty(size=(3, 3))
x
# !garbage in memory

tensor([[-4.4957e-18,  3.0628e-41,  1.5975e-43],
        [ 1.3873e-43,  1.4574e-43,  6.4460e-44],
        [ 1.4153e-43,  1.5274e-43,  1.5695e-43]])

In [14]:
x = torch.zeros(size=(3, 3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
x = torch.ones(size=(3, 3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [16]:
x = torch.rand(size=(3, 3))
x
# !from zero to one with uniform distribution

tensor([[0.4637, 0.1520, 0.5624],
        [0.1637, 0.8363, 0.4821],
        [0.8666, 0.3086, 0.5968]])

In [4]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
x = torch.arange(start=1, end=5, step=1)
x

tensor([1, 2, 3, 4])

In [8]:
x = torch.linspace(start=0.1, end=1, steps=10)
x

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [11]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
x

tensor([[-0.4634, -0.4561, -1.4558,  0.6529,  0.2312]])

In [12]:
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x

tensor([[0.4169, 0.7893, 0.8531, 0.5122, 0.4344]])

In [13]:
x = torch.diag(torch.ones(size=(3, 3)))
x

tensor([1., 1., 1.])

In [15]:
#from different types (int, float, double)
tensor = torch.arange(4)
tensor.bool()

tensor([False,  True,  True,  True])

In [17]:
tensor.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [19]:
tensor.long() #int64

tensor([0, 1, 2, 3])

In [20]:
tensor.half()

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [21]:
tensor.float() #float32

tensor([0., 1., 2., 3.])

In [22]:
tensor.double() 

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [ ]:
# from numpy
import numpy as np
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
np_array_bzck = tensor.numpy()

2. Tensor math & Comparison Operation

In [24]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

In [26]:
#Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
z1

tensor([10., 10., 10.])

In [28]:
z2 = torch.add(x, y)
z2

tensor([10, 10, 10])

In [29]:
z = x + y
z

tensor([10, 10, 10])

In [30]:
#Subtraction
z = x - y
z

tensor([-8, -6, -4])

In [31]:
#Division
z = torch.true_divide(x, y)
z
#element-wize division in case of same sizes

tensor([0.1111, 0.2500, 0.4286])

In [32]:
#Inplace operations - undescore, no copy
t = torch.zeros(3)
t.add_(x)
t

tensor([1., 2., 3.])

In [34]:
t += x
t

tensor([3., 6., 9.])

In [36]:
# Exponentiation
z = x.pow(2)
z

tensor([1, 4, 9])

In [37]:
#Simple comparison
z = x > 0
z

tensor([True, True, True])

In [38]:
#Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2)
x3 # x3 = x1.mm(x2)

tensor([[1.3406, 1.3445, 0.7344],
        [1.8382, 2.1327, 1.2558]])

In [40]:
# matrix exponentiation
matrix_exp = torch.rand((5, 5))
matrix_exp.matrix_power(3)
matrix_exp

tensor([[0.6062, 0.6745, 0.2960, 0.5609, 0.7472],
        [0.2499, 0.8288, 0.1379, 0.7971, 0.1815],
        [0.8086, 0.8165, 0.7830, 0.9621, 0.5127],
        [0.6355, 0.4360, 0.7309, 0.2844, 0.4619],
        [0.4297, 0.8848, 0.2912, 0.3531, 0.2177]])

In [42]:
# Element wise mult
z = x * y
z

tensor([ 9, 16, 21])

In [44]:
#dot product
z = torch.dot(x, y)
z

tensor(46)

In [45]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

In [51]:
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)
assert out_bmm.shape == (batch, n, p)

In [52]:
# Example of Broadcasting
x1 = torch.ones((5, 5)) * 5
x2 = torch.ones((1, 5))
z = x1 - x2 # so it will automatically expanding
z

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [ ]:
# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
values, indeces = torch.max(x, dim=0)
values, indeces = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0)
mean_x = torch.mean(x.float(), dim=0)
z = torch.eq(x, y)
sorted_y, indices = torch.sort(y, dim=0, descending=False)
z = torch.clamp(x, min=0, max=10)

x = torch.tensor([1, 0, 1, 1, 1], dtype=bool)
z = torch.any(x)
z = torch.all(x)




3. Indexing

In [54]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
x[0].shape, x[:, 0].shape

(torch.Size([25]), torch.Size([10]))

In [56]:
x = torch.arange(10)
indices = [2, 5, 8]
x[indices]

tensor([2, 5, 8])

In [57]:
x = torch.arange(10)
x[(x < 2) | (x > 8)]

tensor([0, 1, 9])

In [59]:
x = torch.where(x > 5, x, x*2)
x

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])

In [66]:
x.ndimension(), x.numel()

(1, 10)

4. Tensor Reshaping

In [ ]:
x = torch.arange(9)
x_3x3 = x.view(3, 3)
x_3x3 = x.reshape(3, 3)

In [69]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))
torch.cat((x1, x2), dim=0).shape, torch.cat((x1, x2), dim=1).shape

(torch.Size([4, 5]), torch.Size([2, 10]))

In [70]:
z = x1.view(-1)
z.shape

torch.Size([10])

In [73]:
x = torch.rand((10, 1, 2))
z = x.permute(0, 2, 1)
z.shape

torch.Size([10, 2, 1])

In [ ]:
torch.squeeze()
torch.unsqueeze()

Операции преобразования типа item для извлечения данных из скаляра или tolist() в Python или numpy для перевода в numpy - для required_grad = True тензоров производят операцию аналогичкную detach (осфобождают данные от зависимости к autograd графу, см видео по автограду)